trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: k6_loadtesting_group

steps:
- task: Docker@2
  displayName: Build and Push Docker Image for Sample App
  inputs:
    Dockerfile: $(Build.SourcesDirectory)/sample-app/dockerfile
    command: buildAndPush
    repository: $(acr_name)
    containerRegistry: $(acr_svc)
    tags: |
      v$(Build.BuildId)
      latest

- task: AzureCLI@2
  displayName: "Deploy Perf Test App to ACI"
  inputs:
    azureSubscription: $(acr-sp-svc)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "============== Creating Azure Container Instance ================="
      az container create --name $(aci_name) -g $(resource_group) --image $(acr_name).azurecr.io/$(acr_name):latest \
      --registry-login-server $(acr_name) --registry-username $(acr_name) -n --registry-password $(acr_pswd) --dns-name-label $(aci_name)-01234 --query ipAddress.fqdn