trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: k6_loadtesting_group

steps:
- task: Docker@2
  displayName: Build and Push Docker Image for Sample App
  inputs:
    Dockerfile: $(Build.SourcesDirectory)/sample-app/dockerfile
    command: buildAndPush
    repository: $(acr_name)
    containerRegistry: $(acr_svc)
    tags: |
      v$(Build.BuildId)
      latest